---
- tags: [nextcloud-client-autostart]
  block:

  # cp autostart desktop file
  - when: nextcloud_client_autostart == true
    block:

    # mkdir
    - name: Mkdir {{ nextcloud_client_autostart_dst | dirname }}
      become: true
      ansible.builtin.file:
        path: "{{ nextcloud_client_autostart_dst | dirname }}"
        state: directory
        mode: u=rwx,g=,o=x
        owner: "{{ nextcloud_client_user }}"
        group: "{{ nextcloud_client_user }}"

    # copy
    - name: Copy autostart {{ nextcloud_client_autostart_src }} > {{ nextcloud_client_autostart_dst }}
      become: true
      notify: update-desktop-database
      ansible.builtin.copy:
        src: "{{ nextcloud_client_autostart_src }}"
        dest: "{{ nextcloud_client_autostart_dst }}"
        owner: "{{ nextcloud_client_user }}"
        group: "{{ nextcloud_client_user }}"
        mode: u=rw,g=,o=r # world readable

  # remove autostart
  - when: nextcloud_client_autostart == false 
    name: Remove "{{ nextcloud_client_autostart_dst }}"
    become: true
    ignore_errors: true
    failed_when: false
    ansible.builtin.file:
      path: "{{ nextcloud_client_autostart_dst }}"
      state: absent