---
- name: nextcloud-client role
  tags:
    - nextcloud
    - nextcloud-client
    - nextcloud-desktop
  block:

  # check vars
  - name: Check vars for nextcloud-client role
    ansible.builtin.assert:
      that:
      - nextcloud_client_user != None

  # make sure user exists
  - name: Check if user exists {{ nextcloud_client_user }}
    command: "getent passwd {{ nextcloud_client_user }}"
    changed_when: false

  # flatpak
  - when: nextcloud_client_flatpak_state != None
    ansible.builtin.import_tasks: install_flatpak.yml

  # apt
  - ansible.builtin.import_tasks: install_apt.yml

  # appimage
  - when: nextcloud_client_appimage_state != None
    ansible.builtin.import_tasks: install_appimage.yml

  # autostart
  - ansible.builtin.import_tasks: autostart.yml

  # config
  - ansible.builtin.import_tasks: config.yml